name: ParkCore
version: '1.0'
main: net.ndgwebdesign.parkCore.ParkCore
api-version: '1.21'
authors: [ FriendsparkMC, NDG-webdesign ]

permissions:
  parkcore.admin:
    description: Admin permission for ParkCore
    default: op
    children:
        parkcore.warp.create: true
        parkcore.warp.delete: true
        parkcore.rank.gui: true
        parkcore.rank.create: true
        parkcore.rank.delete: true
        parkcore.rank.permission: true
        parkcore.admin.gui: true
        parkcore.gamemode: true

  parkcore.visitor:
    description: Visitor permission for ParkCore
    default: true
    children:
      parkcore.warp.use: true

  parkcore.gamemode:
    description: Gamemode permission for ParkCore
    default: op
    children:
      parkcore.gm.gms: true
      parkcore.gm.gmc: true
      parkcore.gm.gma: true
      parkcore.gm.gmsp: true

#  normal permissions
  parkcore.warp.use:
    description: Permission to use warps
    default: true

  parkcore.warp.create:
    description: Permission to create warps
    default: op

  parkcore.warp.delete:
      description: Permission to delete warps
      default: op

  parkcore.rank.gui:
    description: Access to Rank GUI
    default: op

  parkcore.rank.create:
    description: Create rank
    default: op

  parkcore.rank.delete:
    description: Delete rank
    default: op

  parkcore.rank.permission:
    description: Manage rank permissions
    default: op

  parkcore.admin.gui:
    description: Access to Admin GUI
    default: op

#  gamemode permissions
  parkcore.gm.gms:
    description: Permission to use /gms
    default: op

  parkcore.gm.gmc:
    description: Permission to use /gmc
    default: op

  parkcore.gm.gma:
    description: Permission to use /gma
    default: op

  parkcore.gm.gmsp:
    description: Permission to use /gmsp
    default: op


commands:
  parkcore:
    description: main command of ParkCore
    usage: /parkcore
    aliases: [pc, park]
  warp:
    description: the warp system of ParkCore
    usage: /warp

  gms:
    description: Set your gamemode to survival
    usage: /gms
    permission: parkcore.gm.gms
  gmc:
    description: Set your gamemode to creative
    usage: /gmc
    permission: parkcore.gm.gmc
  gma:
    description: Set your gamemode to adventure
    usage: /gma
    permission: parkcore.gm.gma
  gmsp:
    description: Set your gamemode to spectator
    usage: /gmsp
    permission: parkcore.gm.gmsp
