name: ParkCore
version: '1.0'
main: net.ndgwebdesign.parkCore.ParkCore
api-version: '1.21'
authors: [ FriendsparkMC, NDG-webdesign ]

commands:
  parkcore:
    description: Hoofdcommand van ParkCore
    usage: /parkcore
    aliases: [pc, park]
permissions:
    parkcore.admin:
        description: Toegang tot alle ParkCore admin commando's
        default: op
    parkcore.reload:
        description: Toegang tot het herladen van de ParkCore configuratie
        default: op