name: ParkCore
version: '1.0'
main: net.ndgwebdesign.parkCore.ParkCore
api-version: '1.21'
authors: [ FriendsparkMC, NDG-webdesign ]

commands:
  parkcore:
    description: main command of ParkCore
    usage: /parkcore
    aliases: [pc, park]
  warp:
    description: the warp system of ParkCore
permissions:
    parkcore.admin:
        description: Admin permission for ParkCore
        default: op
    parkcore.reload:
        description: Toegang tot het herladen van de ParkCore configuratie
        default: op