name: ParkCore
version: '1.0'
main: net.ndgwebdesign.parkCore.ParkCore
api-version: '1.21'
authors: [ FriendsparkMC, NDG-webdesign ]

permissions:
  parkcore.admin:
    description: Admin permission for ParkCore
    default: op
    children:
        parkcore.warp.create: true
        parkcore.warp.delete: true
        parkcore.rank.gui: true

  parkcore.visitor:
    description: Visitor permission for ParkCore
    default: true
    children:
      parkcore.warp.use: true

#  normal permissions
  parkcore.warp.use:
    description: Permission to use warps
    default: true

  parkcore.warp.create:
    description: Permission to create warps
    default: op

  parkcore.warp.delete:
      description: Permission to delete warps
      default: op

  parkcore.rank.gui:
    description: Toegang tot Rank GUI
    default: op

commands:
  parkcore:
    description: main command of ParkCore
    usage: /parkcore
    aliases: [pc, park]
  warp:
    description: the warp system of ParkCore
